const EDUCATION_LEVEL_OPTIONS = [
  { label: 'Primaria', value: 'primary school' },
  { label: 'Secundaria', value: 'secondary school' },
  { label: 'Técnica', value: 'technical' },
  { label: 'Universitario', value: 'university' },
];

const PARENTS_RELATIONSHIP_OPTIONS = [
  { label: 'Casados', value: 'married' },
  { label: 'Unión libre', value: 'common law marriage' },
  { label: 'Madre soltera', value: 'single mother' },
  { label: 'Separados', value: 'separated' },
];

const GRADE_OPTIONS = [
  { label: 'Caminadores', value: 'walkers' },
  { label: 'Párvulos', value: 'toddlers' },
  { label: 'Pre jardín', value: 'preschool' },
  { label: 'Jardín', value: 'kindergarten' },
  { label: 'Transición', value: 'transition' },
  { label: 'Primero', value: 'first grade' },
];

const STRATUM_OPTIONS = [
  { label: '1', value: '1' },
  { label: '2', value: '2' },
  { label: '3', value: '3' },
  { label: '4', value: '4' },
  { label: '5', value: '5' },
  { label: '6', value: '6' },
];

const BLOOD_TYPE_OPTIONS = [
  { label: 'A+', value: 'A+' },
  { label: 'A-', value: 'A-' },
  { label: 'B+', value: 'B+' },
  { label: 'B-', value: 'B-' },
  { label: 'AB+', value: 'AB+' },
  { label: 'AB-', value: 'AB-' },
  { label: 'O+', value: 'O+' },
  { label: 'O-', value: 'O-' },
];

const SISBEN_OPTIONS = [
  { label: 'No tiene', value: 'N/A' },
  { label: 'A1', value: 'A1' },
  { label: 'A2', value: 'A2' },
  { label: 'A3', value: 'A3' },
  { label: 'A4', value: 'A4' },
  { label: 'A5', value: 'A5' },
  { label: 'B1', value: 'B1' },
  { label: 'B2', value: 'B2' },
  { label: 'B3', value: 'B3' },
  { label: 'B4', value: 'B4' },
  { label: 'B5', value: 'B5' },
  { label: 'B6', value: 'B6' },
  { label: 'B7', value: 'B7' },
  { label: 'C1', value: 'C1' },
  { label: 'C2', value: 'C2' },
  { label: 'C3', value: 'C3' },
  { label: 'C4', value: 'C4' },
  { label: 'C5', value: 'C5' },
  { label: 'C6', value: 'C6' },
  { label: 'C7', value: 'C7' },
  { label: 'C8', value: 'C8' },
  { label: 'C9', value: 'C9' },
  { label: 'C10', value: 'C10' },
  { label: 'C11', value: 'C11' },
  { label: 'C12', value: 'C12' },
  { label: 'C13', value: 'C13' },
  { label: 'C14', value: 'C14' },
  { label: 'C15', value: 'C15' },
  { label: 'C16', value: 'C16' },
  { label: 'C17', value: 'C17' },
  { label: 'C18', value: 'C18' },
  { label: 'D1', value: 'D1' },
  { label: 'D2', value: 'D2' },
  { label: 'D3', value: 'D3' },
  { label: 'D4', value: 'D4' },
  { label: 'D5', value: 'D5' },
  { label: 'D6', value: 'D6' },
  { label: 'D7', value: 'D7' },
  { label: 'D8', value: 'D8' },
  { label: 'D9', value: 'D9' },
  { label: 'D10', value: 'D10' },
  { label: 'D11', value: 'D11' },
  { label: 'D12', value: 'D12' },
  { label: 'D13', value: 'D13' },
  { label: 'D14', value: 'D14' },
  { label: 'D15', value: 'D15' },
  { label: 'D16', value: 'D16' },
  { label: 'D17', value: 'D17' },
  { label: 'D18', value: 'D18' },
  { label: 'D19', value: 'D19' },
  { label: 'D20', value: 'D20' },
  { label: 'D21', value: 'D21' },
];

export {
  BLOOD_TYPE_OPTIONS,
  EDUCATION_LEVEL_OPTIONS,
  GRADE_OPTIONS,
  PARENTS_RELATIONSHIP_OPTIONS,
  SISBEN_OPTIONS,
  STRATUM_OPTIONS,
};
